/**
 * Framework adapters (docs/sdks/adapters.md): ≤ a few lines each, no business
 * logic. They re-shape the embedded spec/ schemas (src/specdata/, generated by
 * scripts/sync-spec.mjs) — nothing else.
 */
import { type ToolSpec, TOOL_SPECS } from "./specdata/index.js";

/** The spec/tools/*.json contracts, as plain objects (safe to mutate). */
export function toolSchemas(): ToolSpec[] {
  return structuredClone(TOOL_SPECS);
}

export interface OpenAITool {
  type: "function";
  function: { name: string; description: string; parameters: Record<string, unknown> };
}

/** Tool definitions in the OpenAI function-calling envelope. */
export function openaiTools(): OpenAITool[] {
  return TOOL_SPECS.map((t) => ({
    type: "function",
    function: {
      name: t.name,
      description: t.description,
      parameters: structuredClone(t.input_schema),
    },
  }));
}

export interface AnthropicTool {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

/** Tool definitions in the Anthropic tool-use shape. */
export function anthropicTools(): AnthropicTool[] {
  return TOOL_SPECS.map((t) => ({
    name: t.name,
    description: t.description,
    input_schema: structuredClone(t.input_schema),
  }));
}
