export { ERROR_CODES, ToolError } from "./errors.js";
export { Package, type ContentTypes, type Relationship } from "./opc.js";
export {
  WS_CLASS,
  WS_RUN_RE,
  isWhitespaceChar,
  escapeText,
  escapeAttr,
  decodeEntities,
  nextTag,
  attrs,
  getAttr,
  elementExtent,
  findElement,
  childElements,
  findBody,
  bodyBlocks,
  textPieces,
  scopeText,
  textWithMap,
  pieceAt,
  splice,
  spliceAll,
  needsSpacePreserve,
  emitTextElement,
  type Tag,
  type ElementSlice,
  type TextPiece,
  type SpliceEdit,
} from "./xmlscan.js";
export {
  normalizedText,
  anchorHash,
  paragraphAnchor,
  tableAnchor,
  buildAnchorIndex,
  parseAnchor,
  resolveAnchor,
  type AnchorEntry,
  type ParsedAnchor,
} from "./anchors.js";
export { Session, DocHandle } from "./session.js";
export {
  READ_CHAR_CAP,
  parseStyles,
  parseNumbering,
  parseCommentAuthors,
  projectionContext,
  headingLevel,
  paragraphHeadingLevel,
  annotationTokens,
  decoratedText,
  bodyProjBlocks,
  storyProjBlocks,
  paragraphLine,
  tableDims,
  tableProjection,
  outlineOf,
  parseParagraphRange,
  readProjection,
  searchProjection,
  type NumberingMap,
  type ProjectionContext,
  type ProjBlock,
  type OutlineHeading,
  type OutlineTable,
  type ReadOpts,
  type ReadResult,
  type SearchOpts,
  type SearchMatch,
} from "./projector.js";
export {
  docxOpen,
  docxOutline,
  docxRead,
  docxSearch,
  type DocxOpenArgs,
  type DocxOpenResult,
  type DocxOutlineArgs,
  type DocxOutlineResult,
  type DocxReadArgs,
  type DocxSearchArgs,
  type DocxSearchResult,
} from "./toolsRead.js";
export {
  revisionDate,
  revisionAuthor,
  maxRevisionId,
  revisionOpen,
  emitRun,
  findOccurrences,
  applyPlainMatch,
  applyTrackedReplace,
  diffUnits,
  lcsOps,
  wordDiff,
  diffBlocks,
  rebuildParagraph,
  tToDelText,
  delTextToT,
  scanRevisions,
  revisionMatches,
  resolveRevisions,
  mergeParagraphRuns,
  paragraphBlock,
  type TrackedIds,
  type DiffOp,
  type DiffBlock,
  type Revision,
  type RevisionFilter,
} from "./edits.js";
export {
  docxReplace,
  docxEditParagraph,
  docxInsert,
  docxDelete,
  docxRevision,
  parseMinimalMarkdown,
  type DocxReplaceArgs,
  type DocxReplaceResult,
  type DocxEditParagraphArgs,
  type DocxEditParagraphResult,
  type DocxInsertArgs,
  type DocxInsertResult,
  type DocxDeleteArgs,
  type DocxDeleteResult,
  type DocxRevisionArgs,
  type DocxRevisionFilter,
  type DocxRevisionResult,
  type RevisionEntry,
} from "./toolsEdit.js";
export { validateDoc, repairDoc, isValid, type ValidationIssue } from "./validate.js";
export {
  docxValidate,
  docxRepair,
  docxSave,
  exportBytes,
  type DocxValidateArgs,
  type DocxValidateResult,
  type DocxRepairArgs,
  type DocxRepairResult,
  type DocxSaveArgs,
  type DocxSaveResult,
} from "./toolsLifecycle.js";
export {
  docxTable,
  parseA1,
  colLettersToIndex,
  type DocxTableArgs,
  type DocxTableCell,
  type DocxTableResult,
} from "./tables.js";
export {
  docxStyle,
  docxFormat,
  resolveStyleId,
  applyPStyle,
  mergeIntoStyle,
  type DocxStyleArgs,
  type DocxStyleResult,
  type DocxFormatArgs,
  type DocxFormatResult,
  type StyleRecord,
} from "./styles.js";
export { docxList, type DocxListArgs, type DocxListItem, type DocxListResult } from "./lists.js";
export {
  docxComment,
  commentInitials,
  makeParaId,
  type DocxCommentArgs,
  type DocxCommentEntry,
  type DocxCommentReply,
  type DocxCommentResult,
} from "./comments.js";
export {
  docxSection,
  headerFooterBody,
  type DocxSectionArgs,
  type DocxSectionInfo,
  type DocxSectionMargins,
  type DocxSectionResult,
} from "./sections.js";
export {
  docxMedia,
  cmToEmu,
  drawingRun,
  pngDimensions,
  jpegDimensions,
  type DocxMediaArgs,
  type DocxMediaResult,
} from "./media.js";
export { docxField, type DocxFieldArgs, type DocxFieldResult } from "./fields.js";
export {
  canonicalizeProps,
  runPropsInner,
  paraPropsInner,
  runPropChildren,
  paraPropChildren,
  mergeChildren,
  runPropsEdit,
  paraPropsEdit,
  type CanonProps,
} from "./props.js";
export {
  ensureContentDefault,
  ensureContentOverride,
  ensureStyle,
  addRelationship,
  nextRelId,
  extensionOf,
  styleExists,
  EXT_CONTENT_TYPES,
  TABLE_GRID_STYLE,
  LIST_PARAGRAPH_STYLE,
  COMMENT_REFERENCE_STYLE,
} from "./phase2common.js";
export {
  docxTemplateFill,
  type DocxTemplateFillArgs,
  type DocxTemplateFillResult,
} from "./template.js";
export { docxCreate, parseInline, type DocxCreateArgs, type DocxCreateResult } from "./create.js";
export { docxConvert, type DocxConvertArgs, type DocxConvertResult } from "./convert.js";
export {
  detectSoffice,
  structuralPreview,
  renderToFile,
  renderPreview,
  type RenderResult,
  type PreviewPage,
} from "./render.js";
export {
  docxRenderPreview,
  type DocxRenderPreviewArgs,
  type DocxRenderPreviewResult,
} from "./toolsRender.js";
export { MVP_TOOLS, call, dispatch, defaultSession } from "./dispatch.js";
export {
  toolSchemas,
  openaiTools,
  anthropicTools,
  type OpenAITool,
  type AnthropicTool,
} from "./adapters.js";
export { TOOL_SPECS, ERROR_SPECS, type ToolSpec, type ErrorSpec } from "./specdata/index.js";
export {
  Document,
  DocumentParagraph,
  type EditOptions,
  type ReplaceOptions,
  type InsertOptions,
  type TableOptions,
  type StyleOptions,
  type FormatOptions,
  type ListOptions,
  type SectionOptions,
  type MediaOptions,
  type FieldOptions,
} from "./document.js";
