/** @type {import("@commitlint/types").UserConfig} */
export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-enum": [
      2,
      "always",
      [
        "core",
        "opc",
        "anchors",
        "projector",
        "edit",
        "revisions",
        "comments",
        "tables",
        "styles",
        "validate",
        "render",
        "mcp",
        "py",
        "js",
        "adapters",
        "spec",
        "conformance",
        "bench",
        "docs",
        "examples",
        "ci",
        "deps",
        "release",
      ],
    ],
    "subject-case": [2, "never", ["upper-case", "pascal-case", "start-case"]],
    "body-max-line-length": [0, "always"],
  },
};
