#!/usr/bin/env node
/**
 * Embed the published contract into the package: copies spec/tools/*.json and
 * spec/errors.json into src/specdata/index.ts as a generated module, so
 * toolSchemas()/openaiTools()/anthropicTools() ship the spec verbatim.
 *
 * Run via `pnpm sync-spec`; `pnpm build` chains it automatically.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const specDir = path.resolve(here, "..", "..", "spec");
const outDir = path.resolve(here, "..", "src", "specdata");

const toolFiles = fs
  .readdirSync(path.join(specDir, "tools"))
  .filter((f) => f.endsWith(".json"))
  .sort();
const tools = toolFiles.map((f) =>
  JSON.parse(fs.readFileSync(path.join(specDir, "tools", f), "utf8")),
);
const errors = JSON.parse(fs.readFileSync(path.join(specDir, "errors.json"), "utf8"));

const out = `/**
 * GENERATED by scripts/sync-spec.mjs from spec/tools/*.json and spec/errors.json.
 * Do not edit by hand — run \`pnpm sync-spec\` to regenerate.
 */

export interface ToolSpec {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
  result_schema?: Record<string, unknown>;
  errors?: string[];
}

export interface ErrorSpec {
  code: string;
  category: string;
  message_template: string;
  recovery: string;
}

/** Every spec/tools/*.json contract, in filename (= tool name) order. */
export const TOOL_SPECS: ToolSpec[] = ${JSON.stringify(tools, null, 2)};

/** spec/errors.json — the closed set of structured error payloads. */
export const ERROR_SPECS: ErrorSpec[] = ${JSON.stringify(errors.errors, null, 2)};
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "index.ts"), out);
console.error(
  `sync-spec: embedded ${tools.length} tool schemas and ${errors.errors.length} error specs`,
);
