/**
 * GENERATED by scripts/sync-spec.mjs from spec/tools/*.json and spec/errors.json.
 * Do not edit by hand — run `pnpm sync-spec` to regenerate.
 */

export interface ToolSpec {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
  result_schema?: Record<string, unknown>;
  errors?: string[];
}

export interface ErrorSpec {
  code: string;
  category: string;
  message_template: string;
  recovery: string;
}

/** Every spec/tools/*.json contract, in filename (= tool name) order. */
export const TOOL_SPECS: ToolSpec[] = [
  {
    name: "docx_comment",
    description:
      "Add, reply to, resolve, list, or delete comments, including threaded replies and resolution state. Use op 'list' to discover comment ids like 'C7'; op 'add' anchors the comment to a paragraph found via docx_search or docx_read.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["add", "reply", "resolve", "list", "delete"],
        },
        anchor: {
          type: "string",
          description: "Paragraph anchor like 'P12#e7f8'. Where the comment attaches (op 'add').",
        },
        comment_id: {
          type: "string",
          description: "Comment id like 'C7' (ops 'reply'/'resolve'/'delete').",
        },
        text: {
          type: "string",
          description: "Comment body (ops 'add'/'reply').",
        },
        author: {
          type: "string",
          description: "Comment author for ops 'add'/'reply'. Defaults from environment.",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        comment_id: {
          type: "string",
        },
        anchor: {
          type: "string",
        },
        comments: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
              },
              anchor: {
                type: "string",
              },
              author: {
                type: "string",
              },
              date: {
                type: "string",
              },
              text: {
                type: "string",
              },
              resolved: {
                type: "boolean",
              },
              replies: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    author: {
                      type: "string",
                    },
                    date: {
                      type: "string",
                    },
                    text: {
                      type: "string",
                    },
                  },
                },
              },
            },
          },
        },
        note: {
          type: "string",
        },
      },
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "not_found"],
  },
  {
    name: "docx_convert",
    description:
      "Convert an open document to another format: md/html are produced in-engine (lossless for content, revisions and comments annotated inline) and returned as content; pdf/png go through the render adapter and return a path, never inline bytes. Use docx_open or docx_create first to get a doc_id.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        to: {
          type: "string",
          enum: ["md", "html", "pdf", "png"],
        },
        path: {
          type: "string",
          description:
            "Output path for file-producing targets. Required when to is 'pdf' or 'png'; ignored for 'md' and 'html'.",
        },
      },
      required: ["doc_id", "to"],
    },
    result_schema: {
      type: "object",
      properties: {
        content: {
          type: "string",
          description: "Converted content, returned for 'md' and 'html'.",
        },
        path: {
          type: "string",
          description: "Written output path, returned for 'pdf' and 'png'.",
        },
        renderer: {
          type: "string",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: [
      "doc_not_found",
      "unsupported_format",
      "render_unavailable",
      "render_failed",
      "path_denied",
      "save_failed",
    ],
  },
  {
    name: "docx_create",
    description:
      "Create a new document from Markdown (headings, lists, tables, emphasis) or a structured spec with explicit styles and sections. Returns a doc_id for subsequent edits; output passes the same validation gate as every edit. Provide exactly one of content_md or spec.",
    input_schema: {
      type: "object",
      properties: {
        content_md: {
          type: "string",
          description: "Markdown content for the new document. Mutually exclusive with spec.",
        },
        spec: {
          type: "object",
          description:
            "Structured document spec with explicit styles and sections. Mutually exclusive with content_md.",
        },
      },
      required: [],
    },
    result_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        n_paragraphs: {
          type: "integer",
        },
      },
      required: ["doc_id", "n_paragraphs"],
    },
    errors: ["validation_failed"],
  },
  {
    name: "docx_delete",
    description:
      "Delete a single paragraph by anchor or a contiguous range like 'P14..P16'. With track_changes on, deletion becomes a redline rather than physical removal. Get anchors from docx_search or docx_read first.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        anchor: {
          type: "string",
          description: "Paragraph anchor like 'P12#e7f8'.",
        },
        range: {
          type: "string",
          description: "Paragraph range like 'P14..P16'. Provide anchor or range, not both.",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id"],
    },
    result_schema: {
      type: "object",
      properties: {
        ok: {
          type: "boolean",
        },
        deleted: {
          type: "integer",
          description: "Number of paragraphs deleted.",
        },
      },
      required: ["ok", "deleted"],
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "anchor_not_found"],
  },
  {
    name: "docx_edit_paragraph",
    description:
      "Rewrite a paragraph's full text; with track_changes on, an automatic word-level diff marks only the changed words as a clean redline. Use docx_replace for small in-paragraph substitutions. Get the anchor from docx_search or docx_read first.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        anchor: {
          type: "string",
          description: "Paragraph anchor like 'P12#e7f8'.",
        },
        text: {
          type: "string",
          description: "Replacement text for the whole paragraph.",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "anchor", "text"],
    },
    result_schema: {
      type: "object",
      properties: {
        new_anchor: {
          type: "string",
        },
        diff: {
          type: "string",
          description: "Summary of the word-level diff, e.g. '~3 words changed'.",
        },
      },
      required: ["new_anchor"],
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "anchor_not_found"],
  },
  {
    name: "docx_field",
    description:
      "Insert TOC or page-number field codes, or flag all fields for update. Only the field codes are written — computed values (page numbers, TOC entries) materialize when Word or LibreOffice renders, so never report them as known.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["insert_toc", "insert_page_number", "update"],
        },
        after: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Insert the field after this paragraph (op 'insert_toc').",
        },
        levels: {
          type: "integer",
          default: 3,
          description: "Heading levels the TOC includes (op 'insert_toc').",
        },
        scope: {
          type: "string",
          enum: ["header", "footer"],
          default: "footer",
          description: "Where the page number goes (op 'insert_page_number').",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        new_anchor: {
          type: "string",
        },
        updated: {
          type: "integer",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid"],
  },
  {
    name: "docx_format",
    description:
      "Apply formatting properties to a style_selector (edits the style definition in styles.xml — one change, document-wide effect, idempotent) or as direct formatting on an anchor/range. Prefer style_selector for document-wide changes; use docx_style {op: 'list'} first to discover style names.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        anchor: {
          type: "string",
          description: "Paragraph anchor like 'P12#e7f8'.",
        },
        range: {
          type: "string",
          description:
            "Paragraph range like 'P14..P16'. Provide one of anchor, range, or style_selector.",
        },
        style_selector: {
          type: "object",
          description: "Targets the named style's definition instead of individual paragraphs.",
          properties: {
            style: {
              type: "string",
              description: "Named style like 'Heading 2'.",
            },
          },
          required: ["style"],
        },
        props: {
          type: "object",
          description:
            "Formatting properties to apply: color, bold, italic, size, alignment, spacing, etc.",
          properties: {
            color: {
              type: "string",
              description: "Hex color like '#1F4E79'.",
            },
            bold: {
              type: "boolean",
            },
            italic: {
              type: "boolean",
            },
            size: {
              type: "number",
              description: "Font size in points.",
            },
            alignment: {
              type: "string",
              enum: ["left", "center", "right", "justify"],
            },
            spacing: {
              type: "number",
              description: "Line spacing multiplier.",
            },
          },
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "props"],
    },
    result_schema: {
      type: "object",
      properties: {
        affected: {
          type: "integer",
          description: "Number of paragraphs affected.",
        },
        anchors: {
          type: "array",
          items: {
            type: "string",
          },
        },
        note: {
          type: "string",
        },
      },
      required: ["affected"],
    },
    errors: [
      "doc_not_found",
      "anchor_stale",
      "anchor_invalid",
      "anchor_not_found",
      "style_unknown",
    ],
  },
  {
    name: "docx_insert",
    description:
      "Insert new content after or before an existing paragraph. Content accepts Markdown — headings, blockquotes, horizontal rules, bullet/numbered/task-list (`- [ ]`/`- [x]`) items, and inline bold/italic/code — or plain text; returns one fresh anchor per inserted paragraph. Use docx_read or docx_outline first to find the position anchor.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        after: {
          type: "string",
          description:
            "Insert after this paragraph anchor like 'P12#e7f8'. Provide exactly one of after or before.",
        },
        before: {
          type: "string",
          description:
            "Insert before this paragraph anchor like 'P12#e7f8'. Provide exactly one of after or before.",
        },
        content: {
          type: "string",
          description: "Markdown (multi-paragraph, headings, lists) or plain text.",
        },
        style: {
          type: "string",
          description: "Paragraph style override like 'Heading 3'.",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "content"],
    },
    result_schema: {
      type: "object",
      properties: {
        new_anchors: {
          type: "array",
          items: {
            type: "string",
          },
        },
      },
      required: ["new_anchors"],
    },
    errors: [
      "doc_not_found",
      "anchor_stale",
      "anchor_invalid",
      "anchor_not_found",
      "style_unknown",
    ],
  },
  {
    name: "docx_list",
    description:
      "Create lists, restart or re-level numbering, and convert paragraphs to/from list items — the abstract-numbering indirection in numbering.xml is handled internally. Get target anchors from docx_read or docx_search first.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["create", "restart", "set_level", "convert"],
        },
        anchor: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Single target for ops 'restart'/'set_level'/'convert'.",
        },
        range: {
          type: "string",
          description:
            "Paragraph range like 'P10..P14' to target multiple items instead of a single anchor.",
        },
        after: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Insert the new list after this paragraph (op 'create').",
        },
        kind: {
          type: "string",
          enum: ["ol", "ul"],
          default: "ul",
          description: "Ordered or unordered list (op 'create').",
        },
        items: {
          type: "array",
          description: "List items for op 'create'; 'level' nests multi-level lists.",
          items: {
            type: "object",
            properties: {
              text: {
                type: "string",
              },
              level: {
                type: "integer",
                default: 0,
              },
            },
            required: ["text"],
          },
        },
        at: {
          type: "integer",
          default: 1,
          description: "Value numbering restarts at (op 'restart').",
        },
        level: {
          type: "integer",
          description: "Zero-based list level to assign (op 'set_level').",
        },
        to: {
          type: "string",
          enum: ["ol", "ul", "paragraphs"],
          description:
            "Conversion target (op 'convert'): make the paragraphs list items, or turn list items back into plain paragraphs.",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        new_anchors: {
          type: "array",
          items: {
            type: "string",
          },
        },
        n_affected: {
          type: "integer",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "anchor_not_found"],
  },
  {
    name: "docx_media",
    description:
      "Insert, extract, or replace images — the media part, relationship, and content-type registration are handled as one operation. Insert positions after/before an existing anchor; extract/replace target media ids like 'M2' shown in projections.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["insert", "extract", "replace"],
        },
        after: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Insert the image after this paragraph (op 'insert').",
        },
        before: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Insert the image before this paragraph (op 'insert').",
        },
        image: {
          type: "string",
          description: "Path to the source image file (ops 'insert'/'replace').",
        },
        width_cm: {
          type: "number",
          description:
            "Display width in centimeters; aspect ratio is preserved when height_cm is omitted.",
        },
        height_cm: {
          type: "number",
          description: "Display height in centimeters.",
        },
        media_id: {
          type: "string",
          description: "Media id like 'M2' (ops 'extract'/'replace').",
        },
        path: {
          type: "string",
          description: "Output file path for the extracted image (op 'extract').",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        media_id: {
          type: "string",
        },
        new_anchor: {
          type: "string",
        },
        path: {
          type: "string",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: [
      "doc_not_found",
      "anchor_stale",
      "anchor_invalid",
      "not_found",
      "path_denied",
      "save_failed",
    ],
  },
  {
    name: "docx_open",
    description:
      "Open a .docx file from a path or raw bytes and get a doc_id handle plus a human-readable summary of what the document contains. Call this first — every other tool requires the doc_id it returns. Opening never mutates the file.",
    input_schema: {
      type: "object",
      properties: {
        path: {
          type: "string",
          description: "Filesystem path to the .docx file. Provide path or bytes.",
        },
        bytes: {
          type: "string",
          description: "Base64-encoded .docx file content. Provide path or bytes.",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
    },
    result_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        summary: {
          type: "string",
        },
        n_paragraphs: {
          type: "integer",
        },
        has_tracked_changes: {
          type: "boolean",
        },
        has_comments: {
          type: "boolean",
        },
      },
      required: ["doc_id", "summary", "n_paragraphs", "has_tracked_changes", "has_comments"],
    },
    errors: ["open_failed", "doc_too_large", "malicious_content", "path_denied"],
  },
  {
    name: "docx_outline",
    description:
      "Return the document's heading tree and table list with anchors, resolved through the style cascade. The cheap map of the document — call this right after docx_open on an unfamiliar document, then use the anchors for targeted reads.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id"],
    },
    result_schema: {
      type: "object",
      properties: {
        outline: {
          type: "array",
          items: {
            type: "object",
            properties: {
              anchor: {
                type: "string",
              },
              level: {
                type: "integer",
              },
              text: {
                type: "string",
              },
            },
            required: ["anchor", "level", "text"],
          },
        },
        tables: {
          type: "array",
          items: {
            type: "object",
            properties: {
              anchor: {
                type: "string",
              },
              dims: {
                type: "string",
              },
              after: {
                type: "string",
              },
            },
            required: ["anchor", "dims"],
          },
        },
      },
      required: ["outline", "tables"],
    },
    errors: ["doc_not_found"],
  },
  {
    name: "docx_read",
    description:
      "Read the Markdown projection of a paragraph window, a range, or a whole story (body, footnotes, comments, headers, footers). Use docx_outline or docx_search first to get an anchor; long ranges paginate with a continuation token under the token cap.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        anchor: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Reads this paragraph plus the surrounding window.",
        },
        range: {
          type: "string",
          description: "Paragraph range like 'P10..P24'. Alternative to anchor.",
        },
        window: {
          type: "integer",
          description: "Paragraphs of surrounding context to include around the anchor.",
          default: 0,
        },
        scope: {
          type: "string",
          enum: ["body", "footnotes", "comments", "headers", "footers"],
          default: "body",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id"],
    },
    result_schema: {
      type: "object",
      properties: {
        content: {
          type: "string",
          description:
            "Markdown projection with anchors and salient formatting; resolved run-level formatting when response_format is 'detailed'.",
        },
        continuation: {
          type: "string",
          description: "Continuation token, present when the range was paginated.",
        },
      },
      required: ["content"],
    },
    errors: ["doc_not_found", "anchor_invalid", "anchor_not_found"],
  },
  {
    name: "docx_render_preview",
    description:
      "Render pages of the document to images and return resource links so you can check your own work: render, look, fix. Use at verification checkpoints after a batch of layout-affecting edits, not after every edit — renders cost seconds. The response names the renderer and any font substitutions so you can calibrate trust.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        pages: {
          type: "array",
          items: {
            type: "integer",
          },
          description: "1-based page numbers to render. Omit to render every page.",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id"],
    },
    result_schema: {
      type: "object",
      properties: {
        pages: {
          type: "array",
          items: {
            type: "object",
            properties: {
              page: {
                type: "integer",
              },
              image: {
                type: "string",
                description:
                  "Resource link like 'docx://d1/preview/page-1.png'. Present only when a renderer (LibreOffice) produced an image; omitted in the structural fallback.",
              },
            },
            required: ["page"],
          },
        },
        renderer: {
          type: "string",
        },
        structural: {
          type: "string",
          description:
            "Structural fallback only (renderer 'structural'): the §2 projection of the resolved document with an estimated page count. Present when no render adapter is installed.",
        },
        note: {
          type: "string",
        },
      },
      required: ["pages", "renderer"],
    },
    errors: ["doc_not_found", "render_unavailable", "render_failed"],
  },
  {
    name: "docx_repair",
    description:
      "Mechanically fix what is safe to fix in a broken package (orphaned references, missing content-type entries, duplicate ID renumbering) and report what was fixed and what remains. Run after docx_validate reports errors, then re-validate.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
      },
      required: ["doc_id"],
    },
    result_schema: {
      type: "object",
      properties: {
        fixed: {
          type: "array",
          items: {
            type: "string",
          },
        },
        remaining: {
          type: "array",
          items: {
            type: "string",
          },
        },
      },
      required: ["fixed", "remaining"],
    },
    errors: ["doc_not_found", "repair_incomplete"],
  },
  {
    name: "docx_replace",
    description:
      "Replace text within a paragraph (or all paragraphs), preserving formatting across split runs. Returns the new anchor. Use docx_search first to locate text.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        anchor: {
          type: "string",
          description: "Paragraph anchor like 'P12#e7f8'. Omit to search whole doc.",
        },
        old: {
          type: "string",
        },
        new: {
          type: "string",
        },
        all: {
          type: "boolean",
          default: false,
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "old", "new"],
    },
    result_schema: {
      type: "object",
      properties: {
        new_anchor: {
          type: "string",
        },
        anchors: {
          type: "array",
          items: {
            type: "string",
          },
        },
        n_replaced: {
          type: "integer",
        },
      },
      required: ["n_replaced"],
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "not_found", "ambiguous_target"],
  },
  {
    name: "docx_revision",
    description:
      "List, accept, or reject tracked changes (w:ins/w:del), individually, in bulk, or filtered by author/date. Call op 'list' first to see revision ids, authors, and anchors; accept_all/reject_all are idempotent and all affected anchors come back fresh.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["list", "accept", "reject", "accept_all", "reject_all"],
        },
        id: {
          type: "string",
          description: "Revision id like 'R1' to accept/reject a single revision.",
        },
        filter: {
          type: "object",
          description: "Restrict list/accept/reject to matching revisions.",
          properties: {
            author: {
              type: "string",
            },
            after: {
              type: "string",
              description: "ISO date — only revisions on or after this date.",
            },
            before: {
              type: "string",
              description: "ISO date — only revisions before this date.",
            },
          },
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        revisions: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
              },
              type: {
                type: "string",
                enum: ["ins", "del"],
              },
              author: {
                type: "string",
              },
              date: {
                type: "string",
              },
              anchor: {
                type: "string",
              },
              text: {
                type: "string",
              },
            },
          },
        },
        accepted: {
          type: "integer",
        },
        rejected: {
          type: "integer",
        },
        remaining_by_author: {
          type: "object",
          additionalProperties: {
            type: "integer",
          },
        },
        anchors: {
          type: "array",
          items: {
            type: "string",
          },
        },
        note: {
          type: "string",
        },
      },
    },
    errors: ["doc_not_found", "not_found"],
  },
  {
    name: "docx_save",
    description:
      "Write the document to disk, running the full validation gate first and refusing to write a package that would trigger Word repair. Writes atomically, preserving untouched parts byte-for-byte; saving never closes the doc_id, so keep editing and save again.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        path: {
          type: "string",
        },
      },
      required: ["doc_id", "path"],
    },
    result_schema: {
      type: "object",
      properties: {
        ok: {
          type: "boolean",
        },
        validated: {
          type: "boolean",
        },
        bytes: {
          type: "integer",
        },
      },
      required: ["ok", "validated", "bytes"],
    },
    errors: ["doc_not_found", "validation_failed", "save_failed", "path_denied"],
  },
  {
    name: "docx_search",
    description:
      "Find text in the document and get matching anchors with snippets and surrounding context — never the whole document. Matching runs on coalesced text, so a query split across runs in the XML still hits. Use this to locate targets before docx_read or any edit tool.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        query: {
          type: "string",
        },
        regex: {
          type: "boolean",
          description: "Treat query as a regular expression.",
          default: false,
        },
        scope: {
          type: "string",
          description:
            "Story name ('body', 'footnotes', 'comments', 'headers', 'footers') or paragraph range like 'P10..P24'.",
          default: "body",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id", "query"],
    },
    result_schema: {
      type: "object",
      properties: {
        matches: {
          type: "array",
          items: {
            type: "object",
            properties: {
              anchor: {
                type: "string",
              },
              snippet: {
                type: "string",
              },
              context: {
                type: "string",
              },
            },
            required: ["anchor", "snippet"],
          },
        },
        n_matches: {
          type: "integer",
        },
      },
      required: ["matches", "n_matches"],
    },
    errors: ["doc_not_found", "not_found"],
  },
  {
    name: "docx_section",
    description:
      "Inspect and modify sections: page size, margins, orientation, columns, per-section headers/footers, and section breaks. Sections are addressed by the 'S2' ids surfaced in projections — call op 'list' first to map them.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["list", "set_geometry", "set_header", "set_footer", "insert_break"],
        },
        section: {
          type: "string",
          description:
            "Section id like 'S2' as shown in projections. Defaults to the first section.",
          default: "S1",
        },
        page_size: {
          type: "string",
          enum: ["A3", "A4", "A5", "Letter", "Legal", "Tabloid"],
        },
        orientation: {
          type: "string",
          enum: ["portrait", "landscape"],
        },
        margins: {
          type: "object",
          description: "Margins in centimeters (op 'set_geometry').",
          properties: {
            top: {
              type: "number",
            },
            bottom: {
              type: "number",
            },
            left: {
              type: "number",
            },
            right: {
              type: "number",
            },
          },
        },
        columns: {
          type: "integer",
          description: "Number of text columns (op 'set_geometry').",
        },
        content: {
          type: "string",
          description:
            "Header/footer content as Markdown or plain text (ops 'set_header'/'set_footer').",
        },
        variant: {
          type: "string",
          enum: ["default", "first", "even"],
          default: "default",
          description: "Which header/footer variant to set (ops 'set_header'/'set_footer').",
        },
        after: {
          type: "string",
          description:
            "Paragraph anchor like 'P12#e7f8'. Insert the section break after this paragraph (op 'insert_break').",
        },
        break_type: {
          type: "string",
          enum: ["nextPage", "continuous", "evenPage", "oddPage"],
          default: "nextPage",
          description: "Kind of section break (op 'insert_break').",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        sections: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
              },
              break_type: {
                type: "string",
              },
              page_size: {
                type: "string",
              },
              orientation: {
                type: "string",
              },
              columns: {
                type: "integer",
              },
              has_header: {
                type: "boolean",
              },
              has_footer: {
                type: "boolean",
              },
            },
          },
        },
        section: {
          type: "string",
        },
        new_anchor: {
          type: "string",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "anchor_not_found"],
  },
  {
    name: "docx_style",
    description:
      "List, define, or apply named styles in one consolidated tool. Call op 'list' first — it reports the resolved cascade (based_on chains) — before defining a new style or applying one to a paragraph.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: ["list", "define", "apply"],
        },
        anchor: {
          type: "string",
          description: "Paragraph anchor like 'P12#e7f8'. Target paragraph for op 'apply'.",
        },
        style: {
          type: "string",
          description: "Style name or id to apply (op 'apply').",
        },
        name: {
          type: "string",
          description: "Name of the new style (op 'define').",
        },
        based_on: {
          type: "string",
          description: "Existing style the new definition inherits from (op 'define').",
        },
        props: {
          type: "object",
          description:
            "Formatting properties for op 'define': color, bold, italic, size, alignment, spacing_before, spacing_after, etc.",
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        styles: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: {
                type: "string",
              },
              name: {
                type: "string",
              },
              type: {
                type: "string",
                enum: ["paragraph", "character", "table", "numbering"],
              },
              based_on: {
                type: "string",
              },
              in_use: {
                type: "integer",
              },
            },
          },
        },
        style_id: {
          type: "string",
        },
        new_anchor: {
          type: "string",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: ["doc_not_found", "anchor_stale", "anchor_invalid", "style_unknown"],
  },
  {
    name: "docx_table",
    description:
      "One consolidated tool for all table operations: create, set_cells, insert_row, insert_col, delete_row, delete_col, merge, style, delete. 'create' inserts a table after a paragraph anchor and returns a table anchor like 'T4'; subsequent ops target that anchor. 'style' applies direct table formatting via props (borders, width, alignment, column widths, shading); 'delete' removes the whole table. Cell text supports '\\n' line breaks. Cell addressing accepts zero-based {r, c} pairs or A1 notation.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        op: {
          type: "string",
          enum: [
            "create",
            "set_cells",
            "insert_row",
            "insert_col",
            "delete_row",
            "delete_col",
            "merge",
            "style",
            "delete",
          ],
        },
        anchor: {
          type: "string",
          description: "Table anchor like 'T4'. Required for every op except 'create'.",
        },
        after: {
          type: "string",
          description:
            "Insert the new table after this paragraph anchor like 'P12#e7f8' (op 'create').",
        },
        rows: {
          type: "integer",
          description: "Row count (op 'create').",
        },
        cols: {
          type: "integer",
          description: "Column count (op 'create').",
        },
        data: {
          type: "array",
          description: "Initial cell text by row (op 'create').",
          items: {
            type: "array",
            items: {
              type: "string",
            },
          },
        },
        header: {
          type: "boolean",
          default: false,
          description: "Style the first row as a header row (op 'create').",
        },
        cells: {
          type: "array",
          description:
            "Cells to write (op 'set_cells'). Address each by zero-based {r, c} or A1-style ref.",
          items: {
            type: "object",
            properties: {
              r: {
                type: "integer",
                description: "Zero-based row index.",
              },
              c: {
                type: "integer",
                description: "Zero-based column index.",
              },
              ref: {
                type: "string",
                description: "A1-style cell reference like 'B2'. Alternative to r/c.",
              },
              text: {
                type: "string",
              },
            },
            required: ["text"],
          },
        },
        at: {
          type: "integer",
          description:
            "Zero-based row/column index for insert_row, insert_col, delete_row, delete_col.",
        },
        range: {
          type: "string",
          description: "Cell range in A1 notation like 'A1:C1' (op 'merge').",
        },
        style: {
          type: "string",
          description: "Table style name like 'Table Grid' (ops 'create', 'style').",
        },
        props: {
          type: "object",
          description: "Direct table formatting for op 'style' (overrides the named style).",
          properties: {
            borders: {
              type: "boolean",
              description: "true = single grid borders; false = borderless.",
            },
            border_weight: {
              type: "integer",
              description: "Border line weight in eighths of a point (default 4 = 0.5pt).",
            },
            border_color: {
              type: "string",
              description: "Border hex color like '#1F4E79' (default 'auto').",
            },
            width_pct: {
              type: "number",
              description: "Table width as a percent of the text column (100 = full width).",
            },
            align: {
              type: "string",
              enum: ["left", "center", "right"],
              description: "Horizontal alignment of the table on the page.",
            },
            col_widths: {
              type: "array",
              items: {
                type: "integer",
              },
              description: "Per-column widths in twips; sets a fixed table layout.",
            },
            shading: {
              type: "object",
              description: "Cell fill: { header: hex|null } and/or { all: hex|null }. null clears.",
              properties: {
                header: {
                  type: ["string", "null"],
                },
                all: {
                  type: ["string", "null"],
                },
              },
            },
          },
        },
        track_changes: {
          type: "boolean",
          default: false,
        },
        author: {
          type: "string",
          description: "Revision author when track_changes is true. Defaults from environment.",
        },
      },
      required: ["doc_id", "op"],
    },
    result_schema: {
      type: "object",
      properties: {
        new_anchor: {
          type: "string",
          description: "Table anchor like 'T4@after:P12#e7f8' (op 'create').",
        },
        note: {
          type: "string",
        },
      },
    },
    errors: [
      "doc_not_found",
      "anchor_stale",
      "anchor_invalid",
      "anchor_not_found",
      "style_unknown",
    ],
  },
  {
    name: "docx_template_fill",
    description:
      "Fill a mustache-style template — placeholders, loops, conditions — with data and return the new doc_id. Placeholders fragmented across split runs are coalesced before matching; an empty 'unfilled' list in the result is the success check.",
    input_schema: {
      type: "object",
      properties: {
        template: {
          type: "string",
          description: "Path to the template .docx.",
        },
        data: {
          type: "object",
          description:
            "Merge data: scalars fill placeholders, arrays expand loops, booleans drive conditions.",
        },
        syntax: {
          type: "string",
          enum: ["mustache"],
          default: "mustache",
        },
        strict: {
          type: "boolean",
          default: false,
          description:
            "Fail with placeholder_unfilled instead of leaving placeholders blank when data is missing.",
        },
      },
      required: ["template", "data"],
    },
    result_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        filled: {
          type: "integer",
        },
        loops_expanded: {
          type: "object",
          additionalProperties: {
            type: "integer",
          },
        },
        unfilled: {
          type: "array",
          items: {
            type: "string",
          },
        },
        note: {
          type: "string",
        },
      },
      required: ["doc_id", "filled", "unfilled"],
    },
    errors: ["open_failed", "path_denied", "placeholder_unfilled", "template_syntax"],
  },
  {
    name: "docx_validate",
    description:
      "Check the open document's package integrity (duplicate IDs, broken relationships, revision well-formedness) and report issues with fix hints. Run any time; docx_save runs it for you and refuses to write a broken package. Severity 'warning' issues never block a save.",
    input_schema: {
      type: "object",
      properties: {
        doc_id: {
          type: "string",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          default: "concise",
        },
      },
      required: ["doc_id"],
    },
    result_schema: {
      type: "object",
      properties: {
        valid: {
          type: "boolean",
        },
        issues: {
          type: "array",
          items: {
            type: "object",
            properties: {
              severity: {
                type: "string",
                enum: ["error", "warning"],
              },
              part: {
                type: "string",
              },
              message: {
                type: "string",
              },
              fix_hint: {
                type: "string",
              },
            },
            required: ["severity", "part", "message"],
          },
        },
      },
      required: ["valid", "issues"],
    },
    errors: ["doc_not_found"],
  },
];

/** spec/errors.json — the closed set of structured error payloads. */
export const ERROR_SPECS: ErrorSpec[] = [
  {
    code: "anchor_stale",
    category: "addressing",
    message_template: "Anchor {anchor} is stale: the hash no longer matches the paragraph content.",
    recovery: "Call docx_read {anchor, window} and retry with the fresh anchor.",
  },
  {
    code: "anchor_invalid",
    category: "addressing",
    message_template: "Malformed anchor string: {anchor}.",
    recovery: "Check the format 'P{index}#{hash}'.",
  },
  {
    code: "anchor_not_found",
    category: "addressing",
    message_template: "Anchor {anchor} not found: index out of range or table anchor missing.",
    recovery: "Call docx_outline to re-map anchors.",
  },
  {
    code: "doc_not_found",
    category: "session",
    message_template: "Unknown or expired doc_id: {doc_id}.",
    recovery: "Call docx_open again.",
  },
  {
    code: "open_failed",
    category: "session",
    message_template: "Cannot open {path}: not a valid docx or unreadable path.",
    recovery: "Check the path; the message says what the file actually is.",
  },
  {
    code: "doc_too_large",
    category: "session",
    message_template:
      "Document exceeds configured resource caps (part count, uncompressed size, or compression ratio).",
    recovery: "Split the document, or raise the DOCXENGINE_MAX_* limits if the file is trusted.",
  },
  {
    code: "malicious_content",
    category: "session",
    message_template:
      "Refusing {part}: the package contains hostile content (a DTD/entity declaration or pathological XML nesting).",
    recovery: "Conformant Word documents never declare a DTD; treat this file as untrusted.",
  },
  {
    code: "path_denied",
    category: "session",
    message_template: "Path {path} is outside the server's configured roots.",
    recovery: "Use an allowed path.",
  },
  {
    code: "not_implemented",
    category: "session",
    message_template: "Tool {tool} is not implemented in this build.",
    recovery: "this tool lands in a later phase; see ROADMAP.md",
  },
  {
    code: "invalid_args",
    category: "session",
    message_template: "{tool}: missing required argument(s): {args}.",
    recovery: "Check the tool's input_schema in spec/tools/<tool>.json.",
  },
  {
    code: "not_found",
    category: "edit",
    message_template: "Text not found: {old}.",
    recovery: "Broaden the query; check the projection for the exact text.",
  },
  {
    code: "ambiguous_target",
    category: "edit",
    message_template: "{old} matches {count} times without all: true.",
    recovery: "Add all: true or narrow with an anchor.",
  },
  {
    code: "style_unknown",
    category: "edit",
    message_template: "Named style {style} does not exist.",
    recovery: 'Call docx_style {op: "list"} to see available styles.',
  },
  {
    code: "batch_aborted",
    category: "edit",
    message_template: "Atomic batch aborted: an anchor failed upfront validation.",
    recovery: "Re-read the stale anchors and resubmit the batch.",
  },
  {
    code: "edit_conflict",
    category: "edit",
    message_template: "Concurrent write on doc_id {doc_id} (HTTP transport).",
    recovery: "Retry; edits serialize on the write lock.",
  },
  {
    code: "validation_failed",
    category: "validation",
    message_template: "Package would trigger Word repair; save refused.",
    recovery: "Run docx_repair, then re-validate.",
  },
  {
    code: "repair_incomplete",
    category: "validation",
    message_template: "docx_repair could not fix everything safely.",
    recovery: "Report the items in remaining to the user.",
  },
  {
    code: "save_failed",
    category: "validation",
    message_template: "I/O failure writing output to {path}.",
    recovery: "Check the path and permissions.",
  },
  {
    code: "render_unavailable",
    category: "render",
    message_template: "No render adapter installed.",
    recovery: 'Fall back to docx_convert {to: "md"}; install LibreOffice for visual checks.',
  },
  {
    code: "render_failed",
    category: "render",
    message_template: "Renderer errored on this document.",
    recovery: "See the renderer stderr summary in the response.",
  },
  {
    code: "unsupported_format",
    category: "render",
    message_template: "Unknown convert target: {to}.",
    recovery: "Use md, html, pdf, or png.",
  },
  {
    code: "placeholder_unfilled",
    category: "template",
    message_template: "Data missing for required placeholders (strict mode): {placeholders}.",
    recovery: "Extend data with the listed placeholders.",
  },
  {
    code: "template_syntax",
    category: "template",
    message_template: "Malformed mustache syntax in the template at {placeholder}.",
    recovery: "Fix the offending placeholder identified in the response.",
  },
];
